name: Build Percona XtraDB Cluster 8.0 docs
on:
  push:
    branches: 
      - 8.0 
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.x'
      
      #Configure git
      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV
      #Set up MkDocs
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     #Set up PlantUML
      - name: Setup PlantUML dependencies
        run: |
          sudo apt install -y graphviz 
     
     # Deploy docs
      - name: Deploy docs
        run: |
          mike deploy 8.0 -b publish -p
          mike retitle 8.0 "8.0 (LATEST)" -b publish -p
# - name: Install Node.js 14.x
#        uses: percona-platform/setup-node@v2
#        with:
#          node-version: "14"
#
#      - name: Spelling
#        run: |
#          npx markdown-spellcheck --report --en-us --ignore-acronyms --ignore-numbers "docs/**/*.md" || true
          # Ignore errors, just inspect results
#      - name: Grammar
#        run: |
#          npx write-good --no-passive docs/**/*.md || true
#          # Ignore errors, just inspect results
